### ISSUE TITLE
ngx.log and print not working in the init phase of stream

### ISSUE THREAD

**Issue by ghost** [openresty/stream-lua-nginx-module#221]
```
stream{
    error_log /var/log/nginx/stream_error.log debug;
    init_by_lua_block {
        ngx.log(ngx.DEBUG,"I'm here")
    }
    init_worker_by_lua_block {
        print("I'm here")
    }

    server {
        listen 123 udp;
        lua_code_cache off;
        content_by_lua_file /var/www/test/main.lua;
    }
}
```

openresty/1.19.3.1

no msg output in the error log, but in content_by_lua_file  ngx.log and print both working well.

**Comment by 8kbenchmk** [comment]
I'm sure the code block has been executed, I got msg from /var/log/syslog

```
init_by_lua_block {
    local ffi = require("ffi")
    ffi.cdef[[
        void syslog(int priority, const char *format, ...);
    ]]
    ffi.C.syslog(7, "I'm here")
    ngx.log(ngx.DEBUG,"I'm here")
}
```

**Comment by 8kbenchmk** [comment]
I have read ngx_stream_lua_ngx_log@ngx_stream_lua_log.c
`    r = ngx_stream_lua_get_req(L);

    if (r && r->connection && r->connection->log) {
        log = r->connection->log;
    } else {
        log = ngx_cycle->log;
    }`
it looks that all the log from init phase  will be written to main log, because no any request at this phase.
bu i think it's unreasonable. each log generated from the stream directive should be written to the specified log file.

@agentzh @dndx @spacewander

**Comment by zhuizhuhaomeng** [comment]
I don't think we will fix this issue.
