### ISSUE TITLE
关于使用lua table 共享ngx.req.socket的问题

### ISSUE THREAD

**Issue by alick2011** [openresty/stream-lua-nginx-module#34]
是这样，我现在采用stream-lua 实现 mqtt broker的功能，在采用lua table 存储ngx.req.socket 的时候,在同一个worker进程间，不同的请求上下文中使用共享的socket调用send的方法的时候 出现如下异常

bad request
stack traceback:
coroutine 0:
        [C]: in function 'send'

望大神解答 谢谢

**Comment by agentzh** [comment]
@alick2011 Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

**Comment by agentzh** [comment]
@alick2011 Regarding your question, yes, this limitation is by design. The lifetime of cosockets is bound to the Lua handler context that creates them.

You should use other ways like using a background light thread created by `ngx.timer.at` in `init_worker_by_lua*` and delegate all the backend queries in all the nginx request handlers of the same worker process to that light thread (and use ngx.semaphore to synchronize light threads across the Lua handler boundaries).

**Comment by alick2011** [comment]
@agentzh I try thks
